name: USCIS Case Status Check Action

on:
  schedule:
    # This crontab makes this action scheduled for 23:00 UTC each day
    - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: USCIS Action
        uses: Bluefissure/uscis-case-status-action@v0.1.3
        id: script
        continue-on-error: true
        with:
          receipt_number: ${{ secrets.RECEIPT_NUMBER }}
      - name: Output status.txt
        run: cat status.txt
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Case Status Check Action"
          git add ./status.txt
          git commit -m "${{ steps.script.outputs.status }}"
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Test status is not changed
        uses: pr-mpt/actions-assert@v3
        with:
          assertion: npm://@assertions/is-equal:v1
          actual: "${{ steps.script.outputs.status_changed }}"
          expected: false
